// <auto-generated />
namespace MyEcommerce.Migrations.Application
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_address_for_orders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_address_for_orders));
        
        string IMigrationMetadata.Id
        {
            get { return "202510231044058_add_address_for_orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
