// <auto-generated />
namespace MyEcommerce.Migrations.Application
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class change_product_attribute_table_structure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_product_attribute_table_structure));
        
        string IMigrationMetadata.Id
        {
            get { return "202510200459282_change_product_attribute_table_structure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
