// <auto-generated />
namespace MyEcommerce.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Init_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202510191352412_Init_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
