// <auto-generated />
namespace Day04.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class update_brand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_brand));
        
        string IMigrationMetadata.Id
        {
            get { return "202510130345549_update_brand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
