// <auto-generated />
namespace Day04.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class create_grade_table_and_in_student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_grade_table_and_in_student));
        
        string IMigrationMetadata.Id
        {
            get { return "202510130737503_create_grade_table_and_in_student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
