// <auto-generated />
namespace Day04.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class create_foreign_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_foreign_key));
        
        string IMigrationMetadata.Id
        {
            get { return "202510130447035_create_foreign_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
