// <auto-generated />
namespace Day04.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_student_relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_student_relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202510130710280_add_student_relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
