// <auto-generated />
namespace MyNerdDinner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_application_context : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_application_context));
        
        string IMigrationMetadata.Id
        {
            get { return "202510160202496_update_application_context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
